########################################################################################################################
#                                                                                                                      #
#                                                                                                                      #
#                                    ******   COUNTER - POMPA DI CALORE   ******                                       #
#                                                                                                                      #
#                                                                                                                      #
########################################################################################################################
counter:
  #######################################################################################################################
  # COUNTER DEGLI SBRINAMENTI AVVENUTI DURANTE LA GIORNATA                                                              #
  #######################################################################################################################
  pdc_sbrinamenti:
    name: "Sbrinamenti Pompa di Calore Oggi"
    initial: 0
    step: 1
    restore: true
########################################################################################################################
#                                                                                                                      #
#                                                                                                                      #
#                                 ******   INPUT BOOLEAN - POMPA DI CALORE   ******                                    #
#                                                                                                                      #
#                                                                                                                      #
########################################################################################################################
input_boolean:
  #######################################################################################################################
  # INPUT BOOLEAN DELLO STATO INTERMEDIO OVVERO QUANDO LA POMPA DI CALORE INIZIA LA MODALITA SBRINAMENTO                #
  #######################################################################################################################
  pdc_sbrinamento_monitor:
    name: Monitor Sbrinamento Intermedio PDC
    initial: false
########################################################################################################################
#                                                                                                                      #
#                                                                                                                      #
#                                  ******   AUTOMAZIONI - POMPA DI CALORE   ******                                     #
#                                                                                                                      #
#                                                                                                                      #
########################################################################################################################
automation:
  ########################################################################################################################
  # L'AUTOMAZIONE ATTIVA L'INPUT BOOLEAN SBRINAMENTO MONITOR QUANDO LA POMPA DI CALORE AVVIA LA MODALITÀ SBRINAMENTO     #
  ########################################################################################################################
  - alias: PDC - Attiva Monitor
    triggers:
      - trigger: state
        entity_id: sensor.sbrinamento
        from: "OFF"
        to: "ON"
    actions:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.pdc_sbrinamento_monitor
    mode: single
  ########################################################################################################################
  # L'AUTOMAZIONE INCREMENTA IL COUNTER SBRINAMENTO QUANDO LA POMPA DI CALORE ABBANDONA LA MODALITÀ SBRINAMENTO PER      #
  # RITORNARE NELLA MODALITÀ RISCALDAMENTO                                                                               #
  ########################################################################################################################
  - alias: PDC - Incrementa Counter
    triggers:
      - trigger: state
        entity_id: sensor.sbrinamento
        from: "ON"
        to: "OFF"
    condition:
      - condition: state
        entity_id: input_boolean.pdc_sbrinamento_monitor
        state: "on"
    actions:
      - action: counter.increment
        target:
          entity_id: counter.pdc_sbrinamenti
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.pdc_sbrinamento_monitor
    mode: single